<?php

namespace TextBundle\Repository;

/**
 * SavokaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SavokaRepository extends \Doctrine\ORM\EntityRepository
{
}
